### NUMPY


In [1]:
print("test")

test


In [6]:
import numpy as np

print("LIST")
x = [1,2,3,4,5,6]
print(x)
print("np.array")
arr = np.array(x)
print(arr)

LIST
[1, 2, 3, 4, 5, 6]
np.array
[1 2 3 4 5 6]


In [7]:
arr1 = np.array([2,3,4,5])
print(arr1)

[2 3 4 5]


In [9]:
print(type(x))
print(type(arr1))

<class 'list'>
<class 'numpy.ndarray'>


In [14]:
arr2 = np.array([1,2,3,4,5])
print(arr2[1])
print(arr2[1:4])
print(type(arr2[1:4]))

2
[2 3 4]
<class 'numpy.ndarray'>


In [22]:
# 2차원 배열
y= [[1,2,3], [4,5,6]]
arr3 = np.array(y)
print(arr3)
# 6을 츨력 1챙 2열 ( 0부터 행,열)
print(arr3[1,2])


[[1 2 3]
 [4 5 6]]
6


In [ ]:
# shape : 행, 열 표시 
# 1차원 : 열
# 2차원 : 행, 열
# 아원이 늘어나면 앞으로 늘음
# 3차원 : 차원, 행, 열
print(arr3)
print(arr3.shape)
print(arr2)
print(arr2.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)
[1 2 3 4 5]
(5,)


In [30]:
# array를 변경
arr4 = np.array([1,2,3,4,5,6])
arr5 = arr4.reshape(3,2)
print(arr4)
print(arr5)
print(arr4.reshape(2,3))
print(arr4.reshape(1,6))

[1 2 3 4 5 6]
[[1 2]
 [3 4]
 [5 6]]
[[1 2 3]
 [4 5 6]]
[[1 2 3 4 5 6]]


In [39]:
# 배열 연산
x1 = [1,2,3,4]
y1 = [4,5,6,7]

print(x1+y1)
#print(x1 * y1) # 수치계산 불가

[1, 2, 3, 4, 4, 5, 6, 7]


In [ ]:
# numpy 수치계산
arr11 = np.array(x1)
arr12 = np.array(y1)

print(arr11 + arr12)
print(arr11 * arr12)
print(arr11 / arr12)

[ 5  7  9 11]
[ 4 10 18 28]
[0.25       0.4        0.5        0.57142857]


In [40]:
print(arr11.dtype)

int64


In [45]:
# array.astype( array 형식변경)
arr13 = np.array([1,2,3])
print(arr13.dtype)
arr13_float = arr13.astype('float64')
print(arr13_float)
print(arr13_float.dtype)

int64
[1. 2. 3.]
float64


In [62]:
#reshape (-1, 5) -1 일경우 행을 알아서 만들어 준다. reshape(2,5) 와 같음
#reshape (2, -1) -1일경우 열을 알아서 만들어 준다. reshape(2,5) 와 같음
arr14 = np.arange(10)
print(arr14, arr14.dtype)
arr15 = arr14.reshape(-1,5)
print(arr15)
arr15_1 = arr14.reshape(2,-1)
print(arr15_1)

[0 1 2 3 4 5 6 7 8 9] int64
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1 2 3 4]
 [5 6 7 8 9]]


In [67]:
# 2차원 slice
arr20 = np.arange(1,10)
print(arr20)
arr21 = arr20.reshape(3,3)
print(arr21)

#[0:2, 0:2]
arr31 = arr21[0:2, 0:2]
print(arr31, arr31.shape)
#[1:3, 0:3]
print(arr21[1:3, 0:3])
#[1:3, :]
print(arr21[1:3, :])
#[:,:]
print(arr21[:,:])
#[:2,:1]
print(arr21[:2,:1])
#[:2,0]
print(arr21[:2,0])

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2]
 [4 5]] (2, 2)
[[4 5 6]
 [7 8 9]]
[[4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1]
 [4]]
[1 4]


### 동물별 평균체온과 최대 체중구하기

In [ ]:
import numpy as np

# 체온, 심박수, 체중(kg) 
data = np.array([
    [38.5, 80, 35], #개
    [39.1, 90, 20], #고양이
    [36.8, 60, 400] #말
])

ani = np.array(["개", "고양이", "말"])

#체중, 심박수, 체중 평균값
# axis = 0 행, axis = 1 컬럼
avg_value = data.mean(axis=0)
print(avg_value)

#체중
weight = data[:,2]
print(weight)
#쵀대체중
max_weight = data[:,2].max()
print(max_weight)

max_ani = ani[data[:,2].argmax()]
print(max_ani)

print("동물별 평균 수치 :", avg_value)
print("가장무거운동물   :", max_ani, f"{max_weight} kg")

[ 38.13333333  76.66666667 151.66666667]
[ 35.  20. 400.]
400.0
말
동물별 평균 수치 : [ 38.13333333  76.66666667 151.66666667]
가장무거운동물   : 말 400.0 kg


### 곤충 : 날개수, 다리수, 몸길이(cm)

In [ ]:
data = np.array([
    [2, 6, 1.2],
    [4, 6, 3.4],
    [0, 6, 0.8],
    [0, 8, 2.0]
])

insects = np.array(["나비", "잠자리", "개미", "거미"])

# 다리가 6개인 곤충만 추출
legs = data[data[:,1] == 6]
print(legs)

# 평균 몸길이 구하기
mean_length = data[:,2].mean()
print(mean_length)
print(f"곤충의 평균 몸길이 : ", round(mean_length,2), "cm")

# 날개가 없는 곤충
no_wings = insects[data[:,0] == 0]
#print(no_wings)
print(f"날개없는 곤충 :", no_wings)

[[2.  6.  1.2]
 [4.  6.  3.4]
 [0.  6.  0.8]]
1.8499999999999999
곤충의 평균 몸길이 :  1.85 cm
['개미' '거미']
날개없는 곤충 : ['개미' '거미']
